### PR TITLE
Updated refs, updated version features to C# 6, cleaned up generally.

### PR DESCRIPTION
**Pull request by ghost**
No massive changes, just made the developers job easier, should also fix a bug regarding unable to install via nuget (the .nuspec file needs to be repackaged using nuget pack, then uploaded to nuget.org)

### CODE REVIEW

**Comment by prayzzz** [comment]
There seems to be something wrong with the Newtonsoft.Json dependency. Please check that.

**Comment by ghost** [comment]
I was getting that error before I forked it. I was thinking it was due to unsynced dependencies (in the nuspec and the actual reference), but if it's still broken that's troubling. I'll try to make a sample package with a JSON dependency and see if it works

Regards,

Rhys O'Connor

**Comment by prayzzz** [comment]
The .nuspec and all three packages.config are referencing Newtonsoft.Json 7.0.1. at the moment.
In your PR you forget to adjust the version in SoundCloud.Api.IntegrationTest/packages.config.

**Comment by ghost** [comment]
Ah apologies, I expected that to be automatic

Regards,

Rhys O'Connor

**Comment by prayzzz** [comment]
I still can't accept this PR, since it's not building. It looks like some of the *.csproj files are not correct after updating the dependencies.

**Pull request closed without merging**
